import { ColorPalette } from '../types.js';
import { ansi } from '../ansi.js';

export const darkThemesPart1: Record<string, ColorPalette> = {
  'pure-dark': {
    name: 'pure-dark',
    displayName: 'Minimalist Pure Dark',
    isDark: true,
    category: 'minimal',
    description: 'Pitch black background with neon emerald & cyber cyan',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#10B981') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#EDEDED'),
    dimText: ansi.hex('#666666'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#10B981'),
    accentSecondary: ansi.hex('#06B6D4'),
    border: ansi.hex('#27272A'),
    borderActive: ansi.hex('#10B981'),
    success: ansi.hex('#10B981'),
    danger: ansi.hex('#F43F5E'),
    warning: ansi.hex('#EAB308'),
    info: ansi.hex('#06B6D4'),
    badgeBuy: ansi.bgHex('#10B981') + ansi.hex('#000000') + ansi.bold,
    badgeSell: ansi.bgHex('#F43F5E') + ansi.hex('#FFFFFF') + ansi.bold,
    badgeHold: ansi.bgHex('#27272A') + ansi.hex('#A1A1AA') + ansi.bold,
    badgeSkip: ansi.bgHex('#EAB308') + ansi.hex('#000000') + ansi.bold,
    badgeInfo: ansi.bgHex('#06B6D4') + ansi.hex('#000000') + ansi.bold,
    badgeSuccess: ansi.bgHex('#10B981') + ansi.hex('#000000') + ansi.bold,
    badgeWarning: ansi.bgHex('#EAB308') + ansi.hex('#000000') + ansi.bold,
    badgeError: ansi.bgHex('#F43F5E') + ansi.hex('#FFFFFF') + ansi.bold,
    badgeMemory: ansi.bgHex('#8B5CF6') + ansi.hex('#FFFFFF') + ansi.bold,
    badgeRisk: ansi.bgHex('#06B6D4') + ansi.hex('#000000') + ansi.bold,
  },

  'amber-charcoal': {
    name: 'amber-charcoal',
    displayName: 'Amber Charcoal',
    isDark: true,
    category: 'dark',
    description: 'Warm copper & amber on deep dark background',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#D97706') + ansi.hex('#FFFFFF') + ansi.bold,
    text: ansi.hex('#F4F4F5'),
    dimText: ansi.hex('#71717A'),
    boldText: ansi.bold + ansi.hex('#FAFAFA'),
    accent: ansi.hex('#D97706'),
    accentSecondary: ansi.hex('#F59E0B'),
    border: ansi.hex('#52525B'),
    borderActive: ansi.hex('#D97706'),
    success: ansi.hex('#10B981'),
    danger: ansi.hex('#EF4444'),
    warning: ansi.hex('#F59E0B'),
    info: ansi.hex('#3B82F6'),
    badgeBuy: ansi.bgHex('#065F46') + ansi.hex('#A7F3D0') + ansi.bold,
    badgeSell: ansi.bgHex('#7F1D1D') + ansi.hex('#FECACA') + ansi.bold,
    badgeHold: ansi.bgHex('#3F3F46') + ansi.hex('#E4E4E7') + ansi.bold,
    badgeSkip: ansi.bgHex('#78350F') + ansi.hex('#FDE68A') + ansi.bold,
    badgeInfo: ansi.bgHex('#1E3A8A') + ansi.hex('#BFDBFE') + ansi.bold,
    badgeSuccess: ansi.bgHex('#065F46') + ansi.hex('#A7F3D0') + ansi.bold,
    badgeWarning: ansi.bgHex('#78350F') + ansi.hex('#FDE68A') + ansi.bold,
    badgeError: ansi.bgHex('#7F1D1D') + ansi.hex('#FECACA') + ansi.bold,
    badgeMemory: ansi.bgHex('#581C87') + ansi.hex('#E9D5FF') + ansi.bold,
    badgeRisk: ansi.bgHex('#164E63') + ansi.hex('#A5F3FC') + ansi.bold,
  },

  'tokyo-night': {
    name: 'tokyo-night',
    displayName: 'Tokyo Night',
    isDark: true,
    category: 'dark',
    description: 'Deep navy nightscape with lavender, neon blue & mint',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#7AA2F7') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#C0CAF5'),
    dimText: ansi.hex('#565F89'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#7AA2F7'),
    accentSecondary: ansi.hex('#BB9AF7'),
    border: ansi.hex('#3B4261'),
    borderActive: ansi.hex('#7AA2F7'),
    success: ansi.hex('#9ECE6A'),
    danger: ansi.hex('#F7768E'),
    warning: ansi.hex('#E0AF68'),
    info: ansi.hex('#7DCFFF'),
    badgeBuy: ansi.bgHex('#1B4734') + ansi.hex('#9ECE6A') + ansi.bold,
    badgeSell: ansi.bgHex('#4C171C') + ansi.hex('#F7768E') + ansi.bold,
    badgeHold: ansi.bgHex('#292E42') + ansi.hex('#C0CAF5') + ansi.bold,
    badgeSkip: ansi.bgHex('#4D4719') + ansi.hex('#E0AF68') + ansi.bold,
    badgeInfo: ansi.bgHex('#133B43') + ansi.hex('#7DCFFF') + ansi.bold,
    badgeSuccess: ansi.bgHex('#1B4734') + ansi.hex('#9ECE6A') + ansi.bold,
    badgeWarning: ansi.bgHex('#4D4719') + ansi.hex('#E0AF68') + ansi.bold,
    badgeError: ansi.bgHex('#4C171C') + ansi.hex('#F7768E') + ansi.bold,
    badgeMemory: ansi.bgHex('#38284C') + ansi.hex('#BB9AF7') + ansi.bold,
    badgeRisk: ansi.bgHex('#133B43') + ansi.hex('#7DCFFF') + ansi.bold,
  },

  'solarized-dark': {
    name: 'solarized-dark',
    displayName: 'Solarized Dark',
    isDark: true,
    category: 'dark',
    description: 'Precision low-contrast teal base with amber & cyan accents',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#268BD2') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#93A1A1'),
    dimText: ansi.hex('#586E75'),
    boldText: ansi.bold + ansi.hex('#FDF6E3'),
    accent: ansi.hex('#268BD2'),
    accentSecondary: ansi.hex('#2AA198'),
    border: ansi.hex('#073642'),
    borderActive: ansi.hex('#268BD2'),
    success: ansi.hex('#859900'),
    danger: ansi.hex('#DC322F'),
    warning: ansi.hex('#B58900'),
    info: ansi.hex('#2AA198'),
    badgeBuy: ansi.bgHex('#0A3311') + ansi.hex('#859900') + ansi.bold,
    badgeSell: ansi.bgHex('#3D100F') + ansi.hex('#DC322F') + ansi.bold,
    badgeHold: ansi.bgHex('#073642') + ansi.hex('#93A1A1') + ansi.bold,
    badgeSkip: ansi.bgHex('#332600') + ansi.hex('#B58900') + ansi.bold,
    badgeInfo: ansi.bgHex('#0B3330') + ansi.hex('#2AA198') + ansi.bold,
    badgeSuccess: ansi.bgHex('#0A3311') + ansi.hex('#859900') + ansi.bold,
    badgeWarning: ansi.bgHex('#332600') + ansi.hex('#B58900') + ansi.bold,
    badgeError: ansi.bgHex('#3D100F') + ansi.hex('#DC322F') + ansi.bold,
    badgeMemory: ansi.bgHex('#2B153D') + ansi.hex('#6C71C4') + ansi.bold,
    badgeRisk: ansi.bgHex('#0B3330') + ansi.hex('#2AA198') + ansi.bold,
  }
};
