import { ColorPalette } from '../types.js';
import { ansi } from '../ansi.js';

export const darkThemesPart2: Record<string, ColorPalette> = {
  'monokai-pro': {
    name: 'monokai-pro',
    displayName: 'Monokai Pro',
    isDark: true,
    category: 'dark',
    description: 'Matte charcoal with vibrant lime, sunshine yellow & coral',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#FFD866') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#FCFCFA'),
    dimText: ansi.hex('#727072'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#FFD866'),
    accentSecondary: ansi.hex('#78DCE8'),
    border: ansi.hex('#403E41'),
    borderActive: ansi.hex('#FFD866'),
    success: ansi.hex('#A9DC76'),
    danger: ansi.hex('#FF6188'),
    warning: ansi.hex('#FFD866'),
    info: ansi.hex('#78DCE8'),
    badgeBuy: ansi.bgHex('#223612') + ansi.hex('#A9DC76') + ansi.bold,
    badgeSell: ansi.bgHex('#3F141F') + ansi.hex('#FF6188') + ansi.bold,
    badgeHold: ansi.bgHex('#2D2A2E') + ansi.hex('#FCFCFA') + ansi.bold,
    badgeSkip: ansi.bgHex('#3D3212') + ansi.hex('#FFD866') + ansi.bold,
    badgeInfo: ansi.bgHex('#123236') + ansi.hex('#78DCE8') + ansi.bold,
    badgeSuccess: ansi.bgHex('#223612') + ansi.hex('#A9DC76') + ansi.bold,
    badgeWarning: ansi.bgHex('#3D3212') + ansi.hex('#FFD866') + ansi.bold,
    badgeError: ansi.bgHex('#3F141F') + ansi.hex('#FF6188') + ansi.bold,
    badgeMemory: ansi.bgHex('#2C1B38') + ansi.hex('#AB9DF2') + ansi.bold,
    badgeRisk: ansi.bgHex('#123236') + ansi.hex('#78DCE8') + ansi.bold,
  },

  'catppuccin-mocha': {
    name: 'catppuccin-mocha',
    displayName: 'Catppuccin Mocha',
    isDark: true,
    category: 'dark',
    description: 'Soothing pastel palette with mauve, sky blue & sapphire',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#CBA6F7') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#CDD6F4'),
    dimText: ansi.hex('#6C7086'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#CBA6F7'),
    accentSecondary: ansi.hex('#89DCEB'),
    border: ansi.hex('#313244'),
    borderActive: ansi.hex('#CBA6F7'),
    success: ansi.hex('#A6E3A1'),
    danger: ansi.hex('#F38BA8'),
    warning: ansi.hex('#F9E2AF'),
    info: ansi.hex('#89DCEB'),
    badgeBuy: ansi.bgHex('#1E3822') + ansi.hex('#A6E3A1') + ansi.bold,
    badgeSell: ansi.bgHex('#451A25') + ansi.hex('#F38BA8') + ansi.bold,
    badgeHold: ansi.bgHex('#1E1E2E') + ansi.hex('#CDD6F4') + ansi.bold,
    badgeSkip: ansi.bgHex('#443A23') + ansi.hex('#F9E2AF') + ansi.bold,
    badgeInfo: ansi.bgHex('#18333B') + ansi.hex('#89DCEB') + ansi.bold,
    badgeSuccess: ansi.bgHex('#1E3822') + ansi.hex('#A6E3A1') + ansi.bold,
    badgeWarning: ansi.bgHex('#443A23') + ansi.hex('#F9E2AF') + ansi.bold,
    badgeError: ansi.bgHex('#451A25') + ansi.hex('#F38BA8') + ansi.bold,
    badgeMemory: ansi.bgHex('#341E47') + ansi.hex('#CBA6F7') + ansi.bold,
    badgeRisk: ansi.bgHex('#18333B') + ansi.hex('#89DCEB') + ansi.bold,
  },

  'dracula': {
    name: 'dracula',
    displayName: 'Dracula Dark',
    isDark: true,
    category: 'dark',
    description: 'Iconic gothic dark theme with purple, pink & vibrant cyan',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#BD93F9') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#F8F8F2'),
    dimText: ansi.hex('#6272A4'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#BD93F9'),
    accentSecondary: ansi.hex('#8BE9FD'),
    border: ansi.hex('#44475A'),
    borderActive: ansi.hex('#BD93F9'),
    success: ansi.hex('#50FA7B'),
    danger: ansi.hex('#FF5555'),
    warning: ansi.hex('#FFB86C'),
    info: ansi.hex('#8BE9FD'),
    badgeBuy: ansi.bgHex('#0F3818') + ansi.hex('#50FA7B') + ansi.bold,
    badgeSell: ansi.bgHex('#451212') + ansi.hex('#FF5555') + ansi.bold,
    badgeHold: ansi.bgHex('#282A36') + ansi.hex('#F8F8F2') + ansi.bold,
    badgeSkip: ansi.bgHex('#402A12') + ansi.hex('#FFB86C') + ansi.bold,
    badgeInfo: ansi.bgHex('#16353D') + ansi.hex('#8BE9FD') + ansi.bold,
    badgeSuccess: ansi.bgHex('#0F3818') + ansi.hex('#50FA7B') + ansi.bold,
    badgeWarning: ansi.bgHex('#402A12') + ansi.hex('#FFB86C') + ansi.bold,
    badgeError: ansi.bgHex('#451212') + ansi.hex('#FF5555') + ansi.bold,
    badgeMemory: ansi.bgHex('#321F4C') + ansi.hex('#BD93F9') + ansi.bold,
    badgeRisk: ansi.bgHex('#16353D') + ansi.hex('#8BE9FD') + ansi.bold,
  },

  'one-dark': {
    name: 'one-dark',
    displayName: 'One Dark Pro',
    isDark: true,
    category: 'dark',
    description: 'Atom editor dark palette with soft cyan, blue & chalk white',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#61AFEF') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#ABB2BF'),
    dimText: ansi.hex('#5C6370'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#61AFEF'),
    accentSecondary: ansi.hex('#98C379'),
    border: ansi.hex('#3E4452'),
    borderActive: ansi.hex('#61AFEF'),
    success: ansi.hex('#98C379'),
    danger: ansi.hex('#E06C75'),
    warning: ansi.hex('#E5C07B'),
    info: ansi.hex('#56B6C2'),
    badgeBuy: ansi.bgHex('#1D3316') + ansi.hex('#98C379') + ansi.bold,
    badgeSell: ansi.bgHex('#3D1619') + ansi.hex('#E06C75') + ansi.bold,
    badgeHold: ansi.bgHex('#282C34') + ansi.hex('#ABB2BF') + ansi.bold,
    badgeSkip: ansi.bgHex('#3D3019') + ansi.hex('#E5C07B') + ansi.bold,
    badgeInfo: ansi.bgHex('#142E33') + ansi.hex('#56B6C2') + ansi.bold,
    badgeSuccess: ansi.bgHex('#1D3316') + ansi.hex('#98C379') + ansi.bold,
    badgeWarning: ansi.bgHex('#3D3019') + ansi.hex('#E5C07B') + ansi.bold,
    badgeError: ansi.bgHex('#3D1619') + ansi.hex('#E06C75') + ansi.bold,
    badgeMemory: ansi.bgHex('#351B42') + ansi.hex('#C678DD') + ansi.bold,
    badgeRisk: ansi.bgHex('#142E33') + ansi.hex('#56B6C2') + ansi.bold,
  }
};
