import { ColorPalette } from '../types.js';
import { ansi } from '../ansi.js';

export const nordicThemes: Record<string, ColorPalette> = {
  // ==========================================
  // Gruvbox Dark Retro
  // ==========================================
  'gruvbox-dark': {
    name: 'gruvbox-dark',
    displayName: 'Gruvbox Retro Dark',
    isDark: true,
    category: 'retro',
    description: 'Warm earthy retro tones with terracotta, forest green, and gold',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#FABD2F') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#EBDBB2'),
    dimText: ansi.hex('#928374'),
    boldText: ansi.bold + ansi.hex('#FBF1C7'),
    accent: ansi.hex('#FABD2F'),
    accentSecondary: ansi.hex('#8EC07C'),
    border: ansi.hex('#504945'),
    borderActive: ansi.hex('#FABD2F'),
    success: ansi.hex('#B8BB26'),
    danger: ansi.hex('#FB4934'),
    warning: ansi.hex('#FABD2F'),
    info: ansi.hex('#83A598'),
    badgeBuy: ansi.bgHex('#283B1E') + ansi.hex('#B8BB26') + ansi.bold,
    badgeSell: ansi.bgHex('#471D1B') + ansi.hex('#FB4934') + ansi.bold,
    badgeHold: ansi.bgHex('#3C3836') + ansi.hex('#EBDBB2') + ansi.bold,
    badgeSkip: ansi.bgHex('#473812') + ansi.hex('#FABD2F') + ansi.bold,
    badgeInfo: ansi.bgHex('#1C343B') + ansi.hex('#83A598') + ansi.bold,
    badgeSuccess: ansi.bgHex('#283B1E') + ansi.hex('#B8BB26') + ansi.bold,
    badgeWarning: ansi.bgHex('#473812') + ansi.hex('#FABD2F') + ansi.bold,
    badgeError: ansi.bgHex('#471D1B') + ansi.hex('#FB4934') + ansi.bold,
    badgeMemory: ansi.bgHex('#39233B') + ansi.hex('#D3869B') + ansi.bold,
    badgeRisk: ansi.bgHex('#1C343B') + ansi.hex('#8EC07C') + ansi.bold,
  },

  // ==========================================
  // Nordic Frost Dark
  // ==========================================
  'nord-dark': {
    name: 'nord-dark',
    displayName: 'Nordic Frost Dark',
    isDark: true,
    category: 'nordic',
    description: 'Arctic icy blues, glaciers, and storm clouds',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#88C0D0') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#ECEFF4'),
    dimText: ansi.hex('#7B88A1'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#88C0D0'),
    accentSecondary: ansi.hex('#81A1C1'),
    border: ansi.hex('#4C566A'),
    borderActive: ansi.hex('#88C0D0'),
    success: ansi.hex('#A3BE8C'),
    danger: ansi.hex('#BF616A'),
    warning: ansi.hex('#EBCB8B'),
    info: ansi.hex('#81A1C1'),
    badgeBuy: ansi.bgHex('#2D3F28') + ansi.hex('#A3BE8C') + ansi.bold,
    badgeSell: ansi.bgHex('#452529') + ansi.hex('#BF616A') + ansi.bold,
    badgeHold: ansi.bgHex('#3B4252') + ansi.hex('#ECEFF4') + ansi.bold,
    badgeSkip: ansi.bgHex('#4A4026') + ansi.hex('#EBCB8B') + ansi.bold,
    badgeInfo: ansi.bgHex('#27384A') + ansi.hex('#81A1C1') + ansi.bold,
    badgeSuccess: ansi.bgHex('#2D3F28') + ansi.hex('#A3BE8C') + ansi.bold,
    badgeWarning: ansi.bgHex('#4A4026') + ansi.hex('#EBCB8B') + ansi.bold,
    badgeError: ansi.bgHex('#452529') + ansi.hex('#BF616A') + ansi.bold,
    badgeMemory: ansi.bgHex('#3D2B47') + ansi.hex('#B48EAD') + ansi.bold,
    badgeRisk: ansi.bgHex('#24434D') + ansi.hex('#88C0D0') + ansi.bold,
  },

  // ==========================================
  // Oxide Cloud Shell
  // ==========================================
  'oxide-cloud': {
    name: 'oxide-cloud',
    displayName: 'Oxide Cloud Shell',
    isDark: true,
    category: 'minimal',
    description: 'Clean developer terminal with jade green, slate gray, and crisp white',
    bg: '',
    headerBg: '',
    cardBg: '',
    inputBg: '',
    selectedBg: ansi.bgHex('#2DD4BF') + ansi.hex('#000000') + ansi.noBold,
    text: ansi.hex('#E2E8F0'),
    dimText: ansi.hex('#64748B'),
    boldText: ansi.bold + ansi.hex('#FFFFFF'),
    accent: ansi.hex('#2DD4BF'),
    accentSecondary: ansi.hex('#38BDF8'),
    border: ansi.hex('#334155'),
    borderActive: ansi.hex('#2DD4BF'),
    success: ansi.hex('#34D399'),
    danger: ansi.hex('#FB7185'),
    warning: ansi.hex('#FBBF24'),
    info: ansi.hex('#38BDF8'),
    badgeBuy: ansi.bgHex('#064E3B') + ansi.hex('#34D399') + ansi.bold,
    badgeSell: ansi.bgHex('#4C0519') + ansi.hex('#FB7185') + ansi.bold,
    badgeHold: ansi.bgHex('#1E293B') + ansi.hex('#E2E8F0') + ansi.bold,
    badgeSkip: ansi.bgHex('#451A03') + ansi.hex('#FBBF24') + ansi.bold,
    badgeInfo: ansi.bgHex('#0C4A6E') + ansi.hex('#38BDF8') + ansi.bold,
    badgeSuccess: ansi.bgHex('#064E3B') + ansi.hex('#34D399') + ansi.bold,
    badgeWarning: ansi.bgHex('#451A03') + ansi.hex('#FBBF24') + ansi.bold,
    badgeError: ansi.bgHex('#4C0519') + ansi.hex('#FB7185') + ansi.bold,
    badgeMemory: ansi.bgHex('#3B0764') + ansi.hex('#C084FC') + ansi.bold,
    badgeRisk: ansi.bgHex('#134E4A') + ansi.hex('#2DD4BF') + ansi.bold,
  }
};
